import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

const pretendard = localFont({
  src: "../fonts/Pretendard-Regular.woff",
  variable: "--font-pretendard-sans",
});

export const metadata: Metadata = {
  title: "Smile lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable}`}>
        {children}
      </body>
    </html>
  );
}
